repos:
- name: dot-files
  url: https://github.com/foguinhoperuca/dot-files
  description: Arquivos de configuração pessoais.
- name: foguinhoperuca.github.io
  url: https://github.com/foguinhoperuca/foguinhoperuca.github.io
  description: 
- name: java-commons
  url: https://github.com/foguinhoperuca/java-commons
  description: 
- name: jeff-geo.campos.nom.br
  url: https://github.com/foguinhoperuca/jeff-geo.campos.nom.br
  description: 
- name: agile-java
  url: https://github.com/foguinhoperuca/agile-java
  description: 
- name: YAWECAPP
  url: https://github.com/foguinhoperuca/YAWECAPP
  description: 
- name: snipmate.vim
  url: https://github.com/foguinhoperuca/snipmate.vim
  description: 